<style type="text/css">

/* This stylesheet generated by Transfonter (https://transfonter.org) on March 26, 2018 8:30 PM */

  @font-face {
    font-family: 'MyriadPro-Regular';
    src: url('<?php echo get_template_directory_uri(); ?>/fonts/MyriadPro-Regular.ttf') format('truetype');
    font-weight: 300;
    font-style: normal;
  }

  @font-face {
    font-family: 'BebasNeueLight';
    src: url('<?php echo get_template_directory_uri(); ?>/fonts/BebasNeueLight.ttf') format('truetype');
    font-weight: 300;
    font-style: normal;
  }

  @font-face {
    font-family: 'BebasNeueThin';
    src: url('<?php echo get_template_directory_uri(); ?>/fonts/BebasNeueThin.ttf') format('truetype');
    font-weight: 100;
    font-style: normal;
  }

  @font-face {
    font-family: 'BebasNeueRegular';
    src: url('<?php echo get_template_directory_uri(); ?>/fonts/BebasNeueRegular.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
  }

  @font-face {
    font-family: 'BebasNeueBook';
    src: url('<?php echo get_template_directory_uri(); ?>/fonts/BebasNeueBook.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
  }

  @font-face {
    font-family: 'BebasNeue';
    src: url('<?php echo get_template_directory_uri(); ?>/fonts/BebasNeue.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
  }

  @font-face {
    font-family: 'BebasNeueBold';
    src: url('<?php echo get_template_directory_uri(); ?>/fonts/BebasNeueBold.ttf') format('truetype');
    font-weight: bold;
    font-style: normal;
  }


  font-face {
    font-family: 'OpenSansBold';
    src: url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansBold.ttf");
    src: local("OpenSansBold"), url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansBold.ttf") format("truetype"); }

  @font-face {
    font-family: 'OpenSansBoldItalic';
    src: url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansBoldItalic.ttf");
    src: local("OpenSansBoldItalic"), url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansBoldItalic.ttf") format("truetype"); }

  @font-face {
    font-family: 'OpenSansCondBold';
    src: url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansCondBold.ttf");
    src: local("OpenSansCondBold"), url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansCondBold.ttf") format("truetype"); }

  @font-face {
    font-family: 'OpenSansCondLight';
    src: url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansCondLight.ttf");
    src: local("OpenSansCondLight"), url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansCondLight.ttf") format("truetype"); }

  @font-face {
    font-family: 'OpenSansCondLightItalic';
    src: url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansCondLightItalic.ttf");
    src: local("OpenSansCondLightItalic"), url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansCondLightItalic.ttf") format("truetype"); }

  @font-face {
    font-family: 'OpenSansExtraBold';
    src: url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansExtraBold.ttf");
    src: local("OpenSansExtraBold"), url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansExtraBold.ttf") format("truetype"); }

  @font-face {
    font-family: 'OpenSansExtraBoldItalic';
    src: url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansExtraBoldItalic.ttf");
    src: local("OpenSansExtraBoldItalic"), url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansExtraBoldItalic.ttf") format("truetype"); }

  @font-face {
    font-family: 'OpenSansItalic';
    src: url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansItalic.ttf");
    src: local("OpenSansItalic"), url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansItalic.ttf") format("truetype"); }

  @font-face {
    font-family: 'OpenSansLight';
    src: url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansLight.ttf");
    src: local("OpenSansLight"), url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansLight.ttf") format("truetype"); }

  @font-face {
    font-family: 'OpenSansLightItalic';
    src: url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansLightItalic.ttf");
    src: local("OpenSansLightItalic"), url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansLightItalic.ttf") format("truetype"); }

  @font-face {
    font-family: 'OpenSansRegular';
    src: url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansRegular.ttf");
    src: local("OpenSansRegular"), url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansRegular.ttf") format("truetype"); }

  @font-face {
    font-family: 'OpenSansSemibold';
    src: url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansSemibold.ttf");
    src: local("OpenSansSemibold"), url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansSemibold.ttf") format("truetype"); }

  @font-face {
    font-family: 'OpenSansSemiboldItalic';
    src: url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansSemiboldItalic.ttf");
    src: local("OpenSansSemiboldItalic"), url("<?php echo get_template_directory_uri(); ?>/fonts/OpenSansSemiboldItalic.ttf") format("truetype"); }
    
</style>